/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "mock-api-generator",
  "name": "Mock Forge",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "An API for a vet clinic with owners, pets and appointments",
      "does": "Designs the schema and generates data."
    },
    {
      "say": "Add a nullable microchip number to pets",
      "does": "Edits the schema and regenerates data."
    },
    {
      "say": "Make GET /appointments fail with a 503 half the time",
      "does": "Adds a route override for testing errors."
    }
  ]
};
